### ISSUE TITLE
Could you release the whole code?

### ISSUE THREAD

**Issue by jingfantan** [csxmli2016/DMDNet#3]
Hello,sorry to bother you.I want to know the details about how to accomplish three stages Initialization,Forward Update,Backward Update during training DMDNet.
Before training DMDNet,should I do something about Generic Feature Extractor to finish Initialization stage

**Comment by 2blackbar** [comment]
also change dependenciescause it needs torch with cuda not without it

**Comment by csxmli2016** [comment]
> 
As for initialization, we can randomly select Y images and generate the dictionary items (see Eqn 2). They are the initial features of a generic dictionary. The end-to-end learning will help optimize the generic encoder. Then we can select another Y images to update the generic dictionary, with a forward update in Eqn. 3. Finally, we can remove the generic encoder and regard these generic features as learnable parameters. This is helpful to reduce optimization time. Maybe you can directly generate the generic features with learnable embeddings, then directly optimize them using backward optimization. It will take a longer time to obtain a stable performance. 
The generic feature extractor is randomly initialized before training DMDNet.
