### ISSUE TITLE
test with reference images doesnt really work

### ISSUE THREAD

**Issue by 2blackbar** [csxmli2016/DMDNet#4]
I tried to mix up different faces like matt damon face from 0009 onto women faces, it did 0 difference to the image, if it would work, it would be his facial features on woman's face , am i right ?

**Comment by csxmli2016** [comment]
> I tried to mix up different faces like matt damon face from 0009 onto women faces, it did 0 difference to the image, if it would work, it would be his facial features on woman's face , am i right ?

Suppose that the input image is with clear structures, our specific dictionaries will have little effect on the final results. That is, our model adaptively fused the specific features according to the input images. The end-to-end learning limits our model fully rely on the specific dictioanries.
