### ISSUE TITLE
Size of tensor a must match the size of tensor b 

### ISSUE THREAD

**Issue by C0untFloyd** [csxmli2016/DMDNet#5]
Good job on this enhancer; I'm wondering why it isn't more known...

While experimenting with it, I'm getting this error sometimes:
![grafik](https://github.com/csxmli2016/DMDNet/assets/131583554/31b13971-11b0-4394-8e16-a8923a942172)

I couldn't find out where this comes from, is it because of different image dimensions or missing landmarks?

**Comment by csxmli2016** [comment]
> Good job on this enhancer; I'm wondering why it isn't more known...
> 
> While experimenting with it, I'm getting this error sometimes: ![grafik](https://user-images.githubusercontent.com/131583554/250359702-31b13971-11b0-4394-8e16-a8923a942172.png)
> 
> I couldn't find out where this comes from, is it because of different image dimensions or missing landmarks?

You may check whether the input resolution is right.

**Comment by C0untFloyd** [comment]
Thank you for answering, I've seen the example code resizes small images to 512x512. Is this also the maximum resolution (meaning I need to resize bigger images too) or does it just need to be even dimensions?

**Comment by C0untFloyd** [comment]
Answering myself, always resizing to 512x512 works.
