### ISSUE TITLE
There may be something wrong with the detected component locations.

### ISSUE THREAD

**Issue by Siziff** [csxmli2016/DMDNet#6]
All instructions are executed, but the result is not saved, what could be the matter? 
```
CUDA_VISIBLE_DEVICES=0 python main_test.py -s ./TestExamples/TestGenericRestoration/GenericLists.txt -d ./TestExamples/Results_TestGenericRestoration
Using device : cuda
Model params : 40.36M
Restoring test_face_orig.png with only generic restoration
There may be something wrong with the detected component locations. Continue...
``` 
  File "/usr/local/lib/python3.9/site-packages/torch/nn/functional.py", line 3959, in interpolate
    return torch._C._nn.upsample_bilinear2d(input, output_size, align_corners, scale_factors)
RuntimeError: Input and output sizes should be greater than 0, but got input (H: 0, W: 0) output (H: 40, W: 40)

**Comment by csxmli2016** [comment]
> All instructions are executed, but the result is not saved, what could be the matter?
> 
> ```
> CUDA_VISIBLE_DEVICES=0 python main_test.py -s ./TestExamples/TestGenericRestoration/GenericLists.txt -d ./TestExamples/Results_TestGenericRestoration
> Using device : cuda
> Model params : 40.36M
> Restoring test_face_orig.png with only generic restoration
> There may be something wrong with the detected component locations. Continue...
> ```
> 
> File "/usr/local/lib/python3.9/site-packages/torch/nn/functional.py", line 3959, in interpolate return torch._C._nn.upsample_bilinear2d(input, output_size, align_corners, scale_factors) RuntimeError: Input and output sizes should be greater than 0, but got input (H: 0, W: 0) output (H: 40, W: 40)

Hi, this is mainly caused by the bad landmarks. You can show them on the facial image. When the detected component region is very small, either in width or height, the feature transform process will have an error.
